### ISSUE TITLE
Does't work with external sd card

### ISSUE THREAD

**Issue by liuatgit** [by-syk/UriAnalyser#1]
Choose a file on external sd card. 

the uri:
com.android.externalstorage.documents/document/0000-0000%3Atest%2Fdoc%2Fsample.docx

the path: null

**Comment by by-syk** [comment]
Ok, I'll try to solve it and give you a message as soon.

**Comment by liuatgit** [comment]
Got it work now. It looks like you wrote it, somehow you /* */ it.

                /* else {
                    /*
                     * Like this:
                     *     content://com.android.externalstorage.documents/76DD-33F3:APP/OSBuild.apk
                     * Maybe it's a file from OTG disk.
                     * Sometimes it occurs when the device is equipped with third OS.
                     *
                    result = String.format(Locale.US, "/storage/%1$s/%2$s",
                            PARAS[0], DOCUMENT_ID.substring(PARAS[0].length() + 1));
                }*/
